services:
  hand-tracking-drawing:
    image: flugmaschine/hand-tracking-drawing:latest
    build:
      context: .
    environment:
      DISPLAY: ${DISPLAY:-:0}
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./output:/app/output
    network_mode: host
